language: python
python:
  - "3.7.4"
services: docker
cache: pip
install: "pip install -r requirements.txt"
script:
  - "python server_test.py"
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_LOGIN --password-stdin;
      docker-compose build;
      docker tag server_server:latest "$DOCKER_LOGIN/server:latest";
      docker push "$DOCKER_LOGIN/server:latest";
      make push-image ;
    fi
notifications:
  email: false
