version: '3'
services:
  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis_meow

  redis_meow:
    container_name: redis_meow
    image: redis
    ports:
      - "6379:6379"
