version: '3'
services:
  kvs-socket-server-http:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
